; Fichier généré automatiquement — NE PAS ÉDITER
; Source : interface admin (services_ivr)

[services-ivr]

; Service Commercial
exten => 1001#,1,Answer()
 same => n,Set(SIP_ID=${CALLERID(num)})
 same => n,Set(APPEL_DESTINATION=1001#)
 same => n,AGI(verifier_solde.py)
 same => n,GotoIf($["${AUTORISE}" = "1"]?autorise:refuse)
 same => n(refuse),Playback(custom/solde-insuffisant)
 same => n,Hangup(21)
 same => n(autorise),Queue(commercial_queue)
 same => n,Hangup()

; Support Technique
exten => 1002#,1,Answer()
 same => n,Set(SIP_ID=${CALLERID(num)})
 same => n,Set(APPEL_DESTINATION=1002#)
 same => n,AGI(verifier_solde.py)
 same => n,GotoIf($["${AUTORISE}" = "1"]?autorise:refuse)
 same => n(refuse),Playback(custom/solde-insuffisant)
 same => n,Hangup(21)
 same => n(autorise),Queue(support_queue)
 same => n,Hangup()

; Comptabilite
exten => 1003#,1,Answer()
 same => n,Set(SIP_ID=${CALLERID(num)})
 same => n,Set(APPEL_DESTINATION=1003#)
 same => n,AGI(verifier_solde.py)
 same => n,GotoIf($["${AUTORISE}" = "1"]?autorise:refuse)
 same => n(refuse),Playback(custom/solde-insuffisant)
 same => n,Hangup(21)
 same => n(autorise),Dial(PJSIP/2001,60)
 same => n,Hangup()

; Conference
exten => 1004*,1,Answer()
 same => n,Set(SIP_ID=${CALLERID(num)})
 same => n,Set(APPEL_DESTINATION=1004*)
 same => n,AGI(verifier_solde.py)
 same => n,GotoIf($["${AUTORISE}" = "1"]?autorise:refuse)
 same => n(refuse),Playback(custom/solde-insuffisant)
 same => n,Hangup(21)
 same => n(autorise),ConfBridge(1234)
 same => n,Hangup()
