; Fichier généré automatiquement — NE PAS ÉDITER
; Source : interface admin (utilisateurs par type)

[general]
persistentmembers = yes
autofill = yes

; === COMMERCIAL ===
[commercial_queue]
musicclass = default
strategy = ringall
timeout = 15
retry = 5
maxlen = 10
joinempty = yes
leavewhenempty = yes
announce-position = yes
announce-holdtime = yes

member => PJSIP/3001

; === SUPPORT ===
[support_queue]
musicclass = default
strategy = ringall
timeout = 15
retry = 5
maxlen = 10
joinempty = yes
leavewhenempty = yes
announce-position = yes
announce-holdtime = yes

member => PJSIP/4001

; === COMPTABILITE ===
[comptabilite_queue]
musicclass = default
strategy = ringall
timeout = 15
retry = 5
maxlen = 10
joinempty = yes
leavewhenempty = yes
announce-position = yes
announce-holdtime = yes

member => PJSIP/5001
